### PR TITLE
linux-build label, windows-build label, nuget badge for ScriptCs.Hosting and coverity badge

### PR DESCRIPTION
**Pull request by adamralph**
The coverity badge is static because shields.io doesn't support it yet and their own badge (https://scan.coverity.com/projects/2356/badge.svg?flat=1) doesn't have the right styling.

### CODE REVIEW

**Comment by adamralph** [comment]
rich diff: https://github.com/scriptcs/scriptcs/pull/889/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by khellang** [comment]
Is it time to introduce a table in there? There's quite a bit of badges in the top now. It's wrapping on this screen :stuck_out_tongue_closed_eyes:

**Comment by adamralph** [comment]
As a start we could drop them down a line, to below the 'scriptcs' header.

**Comment by khellang** [comment]
Sure. Ideally I'd like a "build matrix", like this:

| Platform | Status |
| ---------- | -------- |
| Windows | [Windows Build Status](http://ci.scriptcs.net) |
| *NIX | [*nix Build Status](https://travis-ci.org/scriptcs/scriptcs) |
| Coverity | [Coverity Scan Build Status](https://scan.coverity.com/projects/2356) |

**Comment by adamralph** [comment]
I dropped it down a line but it still wraps :unamused:

**Comment by adamralph** [comment]
The table has duplication, i.e. the 'Platform' column and the badge labels.

Perhaps we could split it into two rows, e.g.

[Chocolatey Version](http://chocolatey.org/packages/scriptcs) [Chocolatey Downloads](http://chocolatey.org/packages/scriptcs) [NuGet version (ScriptCs.Hosting)](https://www.nuget.org/packages/ScriptCs.Hosting/)
[*nix Build Status](https://travis-ci.org/scriptcs/scriptcs) [Windows Build Status](http://ci.scriptcs.net) [Coverity Scan Build Status](https://scan.coverity.com/projects/2356)

**Comment by khellang** [comment]
I guess that'll do :smile:

**Pull request merged**
