### PR TITLE
change version from 0.15 to 0.16

### PR DESCRIPTION
**Pull request by khellang**
Ref. #996

### CODE REVIEW

**Comment by adamralph** [comment]
hold until merge from dev to master for 0.15

**Comment by khellang** [comment]
yep :+1:

**Comment by filipw** [comment]
can we avoid created upstream branches for such things?

**Comment by khellang** [comment]
Of course. Why does it matter? Just curious. I'll delete it when it's merged.

**Comment by filipw** [comment]
just to avoid pollution of the upstream - for example my fork has like 40 branches. Times a few contributors it would be a huge mess. imho no one should ever push anything upstream unless it's a common branch approved by the whole team

**Comment by khellang** [comment]
Got rid of the upstream branch. Sorry for polluting. If anyone wants to do a PR from their fork, go ahead.

**Comment by adamralph** [comment]
We may as well leave it until we do the 0.15 release. Given Common.Logging-gate, who knows how far away that's going to be :stuck_out_tongue:

**Pull request closed without merging**
