### PR TITLE
923 refactoring

### LINKED ISSUE #922: scriptcs 0.13.1 crashes when a package has a framework assembly reference
If the packages folder contains a package which has a framework assembly reference, e.g. ScriptCs.Contracts, which references `System.ComponentModel.Composition`, then scriptcs.exe crashes and dies.

This is because, as part of the fix for #913, it's now passing all the assemblies through `AssemblyUtility.IsManagedAssembly()`, which in turn calls `AssemblyName.GetAssemblyName(path)`, but `"System.ComponentModel.Composition"` is not a path, so a `FileNotFoundException` is thrown, and unhandled.

`AssemblyUtility.IsManagedAssembly()` is already catching `BadImageException` and returning false in that case, so I guess it should also catch `FileNotFoundException` and also return false in that case.

Note, that the script pack acceptance test is passing, even with this bug present, because ScriptCs.Adder doesn't take a dependency on ScriptCs.Contracts but ships the DLL in the package instead.

I thought perhaps we'd like to try a 'patch master' approach for this (so dev is free to progress independently in the meantime):

- [x] draft GitHub release (@adamralph)
- [x] raise PR to master (including version bump) (@glennblock and @adamralph)
- [x] merge PR to master (@adamralph)
- [x] publish GitHub release (@adamralph)
- [x] announce (@adamralph)
- [x] merge master to dev (@adamralph)

### PR DESCRIPTION
**Pull request by adamralph**
This is a refactoring of the changes in #923 which fixed #922.

Whilst that PR fixed the bug and allowed us to ship 0.13.2, I was quite uncomfortable leaving `AssemblyUtility.IsManagedAssembly()` returning `true` whenever the the path passed to it isn't rooted and doesn't end in 'dll' or 'exe'. For instance, I could pass `"ThisDoesNotExist.txt"` into it and it would return `true`.

In this PR I've reverted `AssemblyUtility` and instead changed `PackageAssemblyResolver` to filter out unmanaged assemblies from the list returned from `IPackageObject.GetCompatibleDlls()` before concatenating them with `IPackageObject.FrameworkAssemblies`.

IMO the quickest way to review this PR is one commit at a time.

### CODE REVIEW

**Comment by glennblock** [comment]
While true, it is not really an issue as the classes that use
AssemblyUtility only scan dlls and exes. The text file will never get
loaded or indicated as a reference.

I don't have a big concern but I don't think was needed.

**Comment by adamralph** [comment]
It's true that the original fix was fine given all the calls made to `AssemblyUtility.IsManagedAssembly` from the scriptcs codebase, but the method is public and packaged in core, so I think it's important that it conveys the correct semantics. In fact, even if it was internal, I'd still consider this important.

**Comment by adamralph** [comment]
@scriptcs/core does anyone fancy merging this? Are there any concerns? It should be quite quick to review if you take one commit at a time.

**Comment by khellang** [comment]
@adamralph :+1:

**Comment by adamralph** [comment]
woot! thanks @khellang

**Pull request merged**
