### PR TITLE
Hotfix for script-local cache folder

### PR DESCRIPTION
**Pull request by ChrSteinert**
This is a (dirty) fix for #1086. This might be a temporary solution until some further refactoring can be done.

### CODE REVIEW

**Comment by adamralph** [comment]
LGTM. @scriptcs/core any comments?

**Comment by khellang** [comment]
@ChrSteinert Maybe you should add a `// HACK: This is a (dirty) fix for #1086. This might be a temporary solution until some further refactoring can be done.` comment in the code? Otherwise, :shipit:

**Comment by ChrSteinert** [comment]
Sure - added as requested.

**Comment by khellang** [comment]
:+1:

**Comment by adamralph** [comment]
Thanks @ChrSteinert !

**Comment by adamralph** [comment]
@ChrSteinert you've been added to https://github.com/scriptcs/scriptcs/wiki/Contributors :trophy:

**Comment by ChrSteinert** [comment]
That's nice :D 
Alas this fix is sooo small. Maybe the discussion on this will go on any time. Then I'll be there ;)

**Comment by adamralph** [comment]
No contribution is too small :smile:

**Comment by glennblock** [comment]
👍

**Comment by adamralph** [comment]
A tiny :+1: for a tiny contrib :stuck_out_tongue_winking_eye:

**Pull request merged**
