### PR TITLE
Chocolatey installation for multiple users

### PR DESCRIPTION
**Pull request by tillig**
Fix for issue #874. Switched the installation script to use automatic Chocolatey facilities for installing command-line tools. Chocolatey handles putting in a shim to scriptcs.exe and adding the path info. No need for uninstall when using this mechanism - Chocolatey does it all for you.

### CODE REVIEW

**Comment by tillig** [comment]
Testing this is sort of painful and manual, but here's how:

1. Build the solution so the Chocolatey package gets created.
1. Create a temporary folder `C:\temp\temp-scriptcs`.
1. Copy the Chocolatey package `scriptcs.0.12.0.nupkg` into the temp folder.
1. Rename the Chocolatey package from `scriptcs.0.12.0.nupkg` to `scriptcs.1.0.0.zip`. Rename to zip so you can use 7-zip (or other tool) to unpack it; update the number so Chocolatey will eventually think it's more recent than previously released packages.
1. Unpack the zip file into a folder `scriptcs.1.0.0`.
1. Delete the old `scriptcs.1.0.0.zip`.
1. Update the .nuspec in there to say version 1.0.0.
1. Zip up the contents of the folder into a new version of `scriptcs.1.0.0.zip`. Make sure if you browse in the zip file that the .nuspec shows up right in the root of the zip - if you see a folder in there `scriptcs.1.0.0` then you zipped at the wrong level.
1. Rename the .zip file back to `scriptcs.1.0.0.nupkg`.
1. Open up a Powershell script as administrator.
1. Run `choco sources add -name temp-scriptcs -source C:\temp\temp-scriptcs`
1. Run `choco install scriptcs -version "1.0.0"`
1. Watch as the Chocolatey installer runs.
1. Without closing down the Powershell prompt, try using `scriptcs.exe` - it should work.
1. **Open a separate Powershell prompt as a non-admin user (or an otherwise different user than was used to install the package) and run `scriptcs.exe` - it should work for the other user, too.** (This is the bit that got fixed by the PR here.)
1. Browse to `C:\ProgramData\chocolatey\bin` and you'll see a `scriptcs.exe` shim in there.
1. Back at the admin prompt, run `choco uninstall scriptcs`.
1. In `C:\ProgramData\chocolatey\bin` the `scriptcs.exe` shim should be gone.

**Comment by adamralph** [comment]
@tillig thanks very much for this! I really like it, especially the hugely simplified install script! The use of built in chocolatey idioms is a way nicer way to go.

I guess the only downside to this is that it will now require admin rights to install scriptcs. @scriptcs/core how much does this bother us?

**Comment by aarondandy** [comment]
Thank you very much! :+1:

**Comment by tillig** [comment]
Generally packages installed by Chocolatey do seem to require admin rights. It's totally up to y'all, but there's at least precedent for that. (Technically, for me, at least, even installing scriptcs in its current incarnation required admin rights because once you install a package using admin rights, the admin user takes ownership of the chocolatey.log and further non-admin installs become impossible.)

Anyway, if this looks like it'll work and folks are amenable, it'd be pretty helpful for those of us switching between admin and non-admin accounts.

**Comment by aarondandy** [comment]
I get dirty messages from Chocolatey if I don't install things as my other user account with admin privileges. Sometimes, those messages seem accurate.

**Comment by glennblock** [comment]
Nice! I am not too concerned on the admin requirement for chocolatey as it
seems like running as admin is not unreasonable.

**Comment by adamralph** [comment]
@glennblock great - in that case I think we should go ahead and accept this.

@tillig one question first:- how does it behave if an older per-user installation is already present?

**Comment by tillig** [comment]
Just tested it out and apparently [upgrading a package does not actually run the uninstall for the previous version](https://github.com/chocolatey/chocolatey/issues/291) so the way I have it now you'd have to manually uninstall and then reinstall.

Let me see if I can make it just a touch smarter so the upgrade scenario works.

**Comment by tillig** [comment]
I added a block of code that will remove the old %AppData% based install locations and per-user path settings during an upgrade scenario. This allows existing users to upgrade to the new mechanism and new users to install.

It's unfortunate, but [there's no Uninstall-ChocolateyPath](https://github.com/chocolatey/chocolatey/issues/97) in Chocolatey so we can't just use a one-liner to remove the path like was used to install it. Thus you'll see a little bit of manual parsing, but there's really no other way. It's the reverse logic of what's in `Install-ChocolateyPath`.

**Comment by khellang** [comment]
Thanks @tillig! :+1:

**Comment by khellang** [comment]
Added you to the contributors list: https://github.com/scriptcs/scriptcs/wiki/Contributors :smile:

**Comment by khellang** [comment]
BTW, @scriptcs/owners @scriptcs/core: we should really automate that list. Maybe I should add a list as part of the new community blog? Like http://nancyfx.org/contribs.html

**Comment by glennblock** [comment]
@khellang We could host it on the blog and link to it.

**Comment by adamralph** [comment]
It's actually already automated at https://github.com/scriptcs/scriptcs/graphs/contributors

It does require that people commit with their correct email addresses though.

**Comment by tillig** [comment]
Happy to help!

**Comment by ztone** [comment]
Damn, I've been struggling to get on that wiki list for years ... what does a man have to do?

**Comment by adamralph** [comment]
:scream: you weren't on it!?

Fixed :smiley:

**Comment by filipw** [comment]
It's a wiki, it's publicly editable :-)

**Comment by ztone** [comment]
Are you saying that I could have just added myself a long time ago and didn't have to learn to write any code at all. Man, that's several years down the drain.

**Comment by ztone** [comment]
Look ma .. on top of the list 
https://github.com/scriptcs/scriptcs/wiki/Contributors

(sorry for hijacking this thread for such silliness)

**Comment by adamralph** [comment]
@khellang I like your idea of automating the list in a similar way to Nancy and I think you should go for it.

It will be a repitition of https://github.com/scriptcs/scriptcs/graphs/contributors but in a nicer looking and more prominent way.

**Comment by adamralph** [comment]
https://github.com/scriptcs/scriptcs/issues/904

**Pull request merged**
