### PR TITLE
initialize a PaketDirective project

### PR DESCRIPTION
**Pull request by smoothdeveloper**
some instructions to help:

* first run `.paket/paket.bootstrapper.exe prerelease`
* then run `.paket/paket.exe restore` this will restore the file dependency from our visualfsharp PR with paket reference handler
* then build the solution and try to integrate the function I made `ScriptCs.PaketDirective.PaketShim.ResolveLoadScript`

I'm not familiar with build system of this repository, so you'll need to add those two commands:

> if .paket/paket.exe doesn't exist, then run `.paket/paket.bootstrapper.exe prerelease`
> run `.paket/paket.exe restore`

to the build steps (and equivalent invocations with mono for running on *nix)

Notes: 
* In ScriptCs.PaketDirective project, don't touch `ReferenceLoading.PaketHandler.fs` as this is pulled from visualfsharp PR / updated by paket
* the return value of `ScriptCs.PaketDirective.PaketShim.ResolveLoadScript` is a discriminated union, it needs to be pattern matched, in C# this can be done with ` is ` operator, please match on all possible types *at all times*, the types to match on are found in `ReferenceLoading.PaketHandler.fs`, this can also be done by calling methods on `ReferenceLoadingResult` type
* for that thing to work, you most probably need to have the beta release of paket.exe (https://github.com/fsprojects/Paket/releases) in `~/.paket/paket.exe` or somewhere in the folder or parent folders containing the script
* we can tweak PaketShim.fs at will to make it convenient to consume to the C# code according to your needs

ping me on fsharp.org's slack if needed.

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
Related:
* https://github.com/fsharp/fslang-suggestions/issues/542
* https://github.com/scriptcs/scriptcs/issues/845
* https://github.com/Microsoft/visualfsharp/pull/2483
* https://github.com/scriptcs/scriptcs/issues/1220

**Comment by smoothdeveloper** [comment]
Ok build is green now :)

**Comment by smoothdeveloper** [comment]
@jrusbatch it seems F# SDK needs to be installed on teamcity, or some teamcity settings needs to be tweaked.

I think this is the package needed: https://www.microsoft.com/en-us/download/details.aspx?id=48179

**Comment by glennblock** [comment]
This is the error on Team City:

```
 Compilation error: src\ScriptCs.PaketDirective\ScriptCs.PaketDirective.fsproj 
Open in IDE
Z:\buildAgent\work\84dc0ef1e85df67e\src\ScriptCs.PaketDirective\ScriptCs.PaketDirective.fsproj(69, 3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
```

**Comment by glennblock** [comment]
@smoothdeveloper we have a scriptcs slack if you wanna chat about Paket integration / the PR: https://scriptcs-slack.herokuapp.com/

**Comment by glennblock** [comment]
@smoothdeveloper I'll join your slack

**Comment by glennblock** [comment]
Thanks for jumping on this!

**Comment by glennblock** [comment]
@smoothdeveloper let's chat tomorrow about the semantics of `ResolveLoadScript`. I have joined the FSharp slack as `gblock`

**Comment by forki** [comment]
@smoothdeveloper cool stuff. Can you please make it use magic mode (and config file for the prerelease channel). I don't want to introduce bootstrappers anymore.

**Comment by forki** [comment]
Lol who would have predicted that paket's source file Integration will be used to integrate paket itself. Amazing

**Comment by smoothdeveloper** [comment]
> Can you please make it use magic mode (and config file for the prerelease channel). I don't want to introduce bootstrappers anymore.

@forki somehow I tried, but this is first time I tried to use it, it would only download paket v3 rather than v4 beta. If you have chance I gave you commit rights to my fork to try.

@glennblock there is one hack that will need to be implemented in PaketShim.fs (or C# side), it is to replace "main.group.fsx" by "main.group.csx" as the code from visualfsharp just returns that hardcoded string with .fsx.

**Comment by forki** [comment]
Ok will do

Am 26.02.2017 10:46 schrieb "Gauthier Segay" <notifications@github.com>:

**Comment by forki** [comment]
Regarding fsx vs. csx. Can you pr that in my vf# fork to make it a
parameter? Then it's easier downstream.

Am 26.02.2017 10:48 schrieb "Steffen Forkmann" <sforkmann@gmail.com>:

**Comment by smoothdeveloper** [comment]
yes @forki I'll fix this

**Comment by smoothdeveloper** [comment]
@glennblock can you update us whenever, about of first iteration on the PaketShim I've added to the solution?

Let us know how it goes, I'll probably make another round of integration with our updates from the visualfsharp PR when there has been some progress to help integrate the parameters / remove small hack about .fsx => .csx.

Thanks!

**Pull request merged**
