### PR TITLE
Fixes #1172 and #1173

### LINKED ISSUE #1172: Acceptance tests failing on Travis
After a recent checkin, the build failed on Travis running acceptance tests. Testing locally on Windows and OSX works fine. Seems to be related to Travis.

@adamralph any chance you can take a look at this?

### PR DESCRIPTION
**Pull request by glennblock**
* Locks Travis mono build version to 4.2.3.
* Fixes cp command.

### CODE REVIEW

**Comment by glennblock** [comment]
OK so pinning to Mono 4.2.3 seems to have worked. The 2 tests failing are because of the cp command.

**Comment by glennblock** [comment]
doh, my case sensitivity was wrong.

**Comment by glennblock** [comment]
Yay!

**Comment by glennblock** [comment]
@adamralph @ilovezfz pinning indeed fixed it for now.

**Comment by ilovezfs** [comment]
@glennblock nice work :)

**Comment by glennblock** [comment]
@ilovezfs it won't fix it for brew though as you said because of the mono version.

**Comment by glennblock** [comment]
@ilovezfs based on where the test is failing, it really looks like it is a very specific issue related to how mono is returning the stdout stream. The likelihood is that scriptcs itself will work fine. Do you want me to create for you the brew build.sh file?

**Comment by ilovezfs** [comment]
@glennblock that would be great.

**Comment by glennblock** [comment]
@ilovezfs just committed build_brew.sh to dev, and master. It doesn't affect our release, so there was no problem just committing to master.

**Comment by glennblock** [comment]
Yippee!

screen shot 2016-09-06 at 1 32 33 am

**Comment by ilovezfs** [comment]
@glennblock awesome :green_heart:

**Comment by glennblock** [comment]
Thanks for the help!

**Pull request merged**
