### PR TITLE
Updated to Roslyn 2.2.0

### PR DESCRIPTION
**Pull request by filipw**
No new features for us, but some small bug fixes. This is the latest stable version. (2.3.0 is in preview atm)

### CODE REVIEW

**Review by khellang — APPROVED** [review]

**Comment by filipw** [comment]
:shipit: :shipit: :shipit:

**Comment by glennblock** [comment]
Sorry, missed this, but looks good.

**Comment by filipw** [comment]
let's move it to master and release :1st_place_medal:

**Comment by glennblock** [comment]
I think we need to do some validation first. I know we are behind on this, but let's make it happen. A few months ago when I tried I think some things were broken.

**Pull request merged**
