### PR TITLE
Adding custom package manager to allow forcing framework target version

### PR DESCRIPTION
**Pull request by glennblock**
Fix for #1213

### CODE REVIEW

**Comment by daveaglick** [comment]
One suggestion I have would be to consider pulling the `FrameworkName` from either the current assembly or a known assembly instead of baking it in. That way you won't need to remember to change it if/when running on different frameworks.

See here for an example: https://github.com/Wyamio/Wyam/blob/353f72a84cea7c2747517e3b534fa8d8aaaa5fc2/src/core/Wyam.Configuration/NuGet/PackageInstaller.cs#L42

**Comment by glennblock** [comment]
Right now we only support one, but that is a good point to consider if we end up getting support for .NET Core at some point.

**Comment by glennblock** [comment]
@daveaglick does it make sense for us to upgrade to the NuGet 3 client? Currently we only support .NET 4.5, though we are going to move to require 4.6 soon.

**Comment by glennblock** [comment]
@daveaglick thanks for the link, I will use that approach.

**Comment by daveaglick** [comment]
So are you still on the v2 NuGet APIs? If so, I would suggest moving to v3. AFAIK, the v2 APIs aren't getting any more love. There's a lot of breakage though. I'll take a look tomorrow to see what it might take to bump you up.

**Comment by glennblock** [comment]
@daveaglick updated. Works beautifully, thanks!

**Comment by glennblock** [comment]
Allright, based on all MY testing (and the fact that Travis and TC pass) I am going to just go and merge this. I'll ask for forgiveness later if that was a bad idea.

**Pull request merged**
