### PR TITLE
Add null checks to AppDomainAssemblyResolver constructor

### PR DESCRIPTION
**Pull request by scottcarr**
Hello,  I thought you might like to add null checks to the arguments of this constructor.

FYI, I found these missing checks with a static analysis tool I'm working on based on CodeContracts and Roslyn.  I can run it over the whole repo and provide the full output if you're interested.  If you're interested in running the tool yourself, it is open source and on github.  I'll be making the repo public soon. Thanks!

### CODE REVIEW

**Comment by adamralph** [comment]
@scottcarr thank you! Would you mind combining the commits into one?

**Comment by scottcarr** [comment]
I merged the commits, but now travis-ci is failing.  Any ideas?

**Comment by adamralph** [comment]
Travis CI is sketchy, don't worry about it.

You seemed to have performed a merge. All you had to do was squish the two commits into one, no need for any merging.

**Comment by scottcarr** [comment]
I'm not that great at git yet! Could you please tell me how to squish that commits in the way you thought I would?  This is what I did (approximately):

git rebase -i <the commit before my commit>
(then I think I had to fix some merge conflicts because had I renamed a variable)
git push -f

Is that correct?  (I may have done other things because I rebased the wrong commits the first time).

**Comment by adamralph** [comment]
I guess you must have force pushed again since it looks fine now.

**Comment by adamralph** [comment]
@scottcarr thanks again! I've added you to https://github.com/scriptcs/scriptcs/wiki/Contributors :trophy:

**Pull request merged**
