### PR TITLE
Changes ModuleLoader to ignore native assemblies. Fix for #913

### PR DESCRIPTION
**Pull request by glennblock**

### CODE REVIEW

**Comment by glennblock** [comment]
@adamralph looks like Travis CI timed out trying to install some packages.

**Comment by adamralph** [comment]
Yeah, TravisCI does that sometimes. A re-run usually works.

It looks like there are some genuine failures in the unit tests right now. (TravisCI doesn't run the unit tests yet.)

**Comment by glennblock** [comment]
Yeah I am fixing them.

**Comment by glennblock** [comment]
Testing the test fixes now.

**Comment by glennblock** [comment]
@sbedford THIS should work!

**Comment by adamralph** [comment]
fixes #913

**Pull request merged**
