### PR TITLE
Hotfix NuGet.Core package reference

### PR DESCRIPTION
**Pull request by jrusbatch**
This PR applies the changes made in c5048547cf70fc07dd13a72745d3f4d492260386 and 115f2e6afdbcc3ea354ab7cec412ae44d66c3611 (introduced to the dev branch in #1019) directly to the master branch for a hotfix release.

### CODE REVIEW

**Comment by khellang** [comment]
That Travis build is driving me nuts! @jrusbatch this is good to go, right?

**Comment by adamralph** [comment]
I'm re-running it but yeah, it's just the usual problem over at Travis

**Comment by jrusbatch** [comment]
@khellang Yeah. I don't see anything holding it back.

**Comment by adamralph** [comment]
Fly little package... fly fly

**Comment by adamralph** [comment]
I published a GitHub release (inc. tag on master)

**Comment by glennblock** [comment]
LOL Adam you crack me up.

**Pull request merged**
