### PR TITLE
made Namespaces collection immutable and relevant methods virtual #1040

### LINKED ISSUE #1040: Make ScriptExecutor namespaces immutable and make import/remove methods virtual
See discussions here: #1036

1) Replace ```IScriptExecutor.Namespaces``` with ```IReadOnlyCollection<string> Namespaces { get; }``` (Possibly a breaking change if people add namespaces directly to this collection, but they shouldn't be anyhow)

2) make Import / Remove Namespaces methods virtual

Any input? Will prep PR

### PR DESCRIPTION
**Pull request by adamralph**
closes #1040

### CODE REVIEW

**Comment by adamralph** [comment]
As an aside, it seems like Travis CI has become a lot more stable all of a sudden. All builds seem to be green on the first build.

**Comment by lukebuehler** [comment]
@adamralph, thanks! sorry about this.

**Comment by glennblock** [comment]
@adamralph anything holding this up from merging?

**Comment by adamralph** [comment]
@glennblock nope, good to go. Assuming we are OK with the breaking change to `IScriptExecutor`. The `Namespaces` property is changing from `Collection<string>` to `IReadOnlyCollection<string>`.

**Comment by glennblock** [comment]
Ugh breaking change. That will break all hosts.

**Comment by glennblock** [comment]
OK having thought this over, it seems reasonable. If it breaks hosts, it will be minor change in the code.

**Comment by glennblock** [comment]
Looks like suddenly this is breaking the build

**Comment by glennblock** [comment]
Well I ran the build locally and worked fine with all acceptance tests. It may be a Travis acting up.

**Pull request merged**
