### PR TITLE
Add support for dynamic. 

### LINKED ISSUE #1110: Compilation error using dynamic
Given the following code:

```csharp
dynamic foo = new System.Dynamic.ExpandoObject();
foo.bar="baz";
```

When compiling you will get the following error:

```text
(1,1): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
```

Looks like a reference is missing

### PR DESCRIPTION
**Pull request by glennblock**
Fixes #1110

### CODE REVIEW

**Comment by glennblock** [comment]
WHY DID YOU MERGE THIS, THE COMMITS ARE NOT IN ORDER???

**Comment by khellang** [comment]
WHY DID YOU OPEN THIS PULL REQUEST!?? :stuck_out_tongue_closed_eyes: They look fine to me. The build and all tests pass :grin:

**Comment by glennblock** [comment]
HA HA ZING! We're just pulling your chain!

**Comment by khellang** [comment]
I'll stop merging pull requests then... :sob:

**Comment by glennblock** [comment]
I did want to rebase, to squash the commits :-)

**Comment by khellang** [comment]
Meh. I was thinking about leaving a nit comment on squashing the last two commits, but couldn't bother. Didn't know you were literally staring at this PR when I merged it :stuck_out_tongue:

**Comment by glennblock** [comment]
@khellang Just giving you a hard time, @filipw came up with that comment :-)

**Comment by khellang** [comment]
I my :heart: just skipped a couple of beats :confounded:

**Comment by glennblock** [comment]
@filipw says "Winning!" :-)

**Pull request merged**
