### PR TITLE
fix failed install output

### LINKED ISSUE #1114: scriptcs -install gives a very verbose error for package not found
In scriptcs version 0.14.1 installing a package that does not exist gives a nice compact error

```
gbmac:test glennblock$ scriptcs -install footest
Installing packages...
ERROR: Unable to find package 'footest'.
ERROR: Package installation failed: One or more errors occurred.
```

In 0.15.0 this error got very ugly.

```
ERROR: Error installing package. [InvalidOperationException] Unable to find package 'scriptcs.calculator'.
ERROR: Package installation failed: System.AggregateException: One or more errors occurred ---> System.InvalidOperationException: Unable to find package 'scriptcs.calculator'.
  at NuGet.PackageRepositoryHelper.ResolvePackage (IPackageRepository sourceRepository, IPackageRepository localRepository, IPackageConstraintProvider constraintProvider, System.String packageId, NuGet.SemanticVersion version, Boolean allowPrereleaseVersions) [0x00000] in <filename unknown>:0
  at NuGet.PackageRepositoryHelper.ResolvePackage (IPackageRepository sourceRepository, IPackageRepository localRepository, System.String packageId, NuGet.SemanticVersion version, Boolean allowPrereleaseVersions) [0x00000] in <filename unknown>:0
  at NuGet.PackageManager.InstallPackage (System.String packageId, NuGet.SemanticVersion version, Boolean ignoreDependencies, Boolean allowPrereleaseVersions) [0x00000] in <filename unknown>:0
  at ScriptCs.Hosting.Package.NugetInstallationProvider.InstallPackage (IPackageReference packageId, Boolean allowPreRelease) [0x00000] in <filename unknown>:0
  at ScriptCs.Hosting.Package.PackageInstaller.InstallPackages (IEnumerable`1 packageIds, Boolean allowPreRelease) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at ScriptCs.Hosting.Package.PackageInstaller.InstallPackages (IEnumerable`1 packageIds, Boolean allowPreRelease) [0x00000] in <filename unknown>:0
  at ScriptCs.Command.InstallCommand.Execute () [0x00000] in <filename unknown>:0
 --> (Inner exception 0) System.InvalidOperationException: Unable to find package 'scriptcs.calculator'.
  at NuGet.PackageRepositoryHelper.ResolvePackage (IPackageRepository sourceRepository, IPackageRepository localRepository, IPackageConstraintProvider constraintProvider, System.String packageId, NuGet.SemanticVersion version, Boolean allowPrereleaseVersions) [0x00000] in <filename unknown>:0
  at NuGet.PackageRepositoryHelper.ResolvePackage (IPackageRepository sourceRepository, IPackageRepository localRepository, System.String packageId, NuGet.SemanticVersion version, Boolean allowPrereleaseVersions) [0x00000] in <filename unknown>:0
  at NuGet.PackageManager.InstallPackage (System.String packageId, NuGet.SemanticVersion version, Boolean ignoreDependencies, Boolean allowPrereleaseVersions) [0x00000] in <filename unknown>:0
  at ScriptCs.Hosting.Package.NugetInstallationProvider.InstallPackage (IPackageReference packageId, Boolean allowPreRelease) [0x00000] in <filename unknown>:0
  at ScriptCs.Hosting.Package.PackageInstaller.InstallPackages (IEnumerable`1 packageIds, Boolean allowPreRelease) [0x00000] in <filename unknown>:0
```

We should trap this hideous error and put back a nice message

### PR DESCRIPTION
**Pull request by adamralph**
fixes #1114 

image

### CODE REVIEW

**Comment by filipw** [comment]
you should unwrap or hide the AggregateException

**Comment by adamralph** [comment]
This PR fixes the bug. We can talk about how to unwrap separately.

**Comment by glennblock** [comment]
First awesome!

Second, we should probably have a generic utility to do unwrapping.

**Comment by adamralph** [comment]
We probably should do something with the aggregate exception, but we can spin off a separate issue for that.

This PR fixes the bug #1114 and should be good to merge.

**Comment by khellang** [comment]
For reference; https://github.com/NancyFx/Nancy/blob/master/src/Nancy/Helpers/ExceptionExtensions.cs

**Comment by glennblock** [comment]
Thanks @adamralph

**Pull request merged**
