### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vasily-kirichenko**

### CODE REVIEW

**Comment by forki** [comment]
this touched the readme so I guess CI error is unrelated

**Comment by glennblock** [comment]
Yeah, our Travis build is flaky due to xunit path issues on OSX

**Comment by forki** [comment]
get rid of xunit then ;-)

**Comment by glennblock** [comment]
It's crossed my mind, but porting all our unit and acceptance tests will be
a pain, and I say that lightly.

**Comment by glennblock** [comment]
Thanks @vasily-kirichenko!

**Pull request merged**
