### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by chergey**
refactored code to take advantage of expression body, changed LanguageVersion to CSharp7_1,  https://github.com/scriptcs/scriptcs/issues/1250

### CODE REVIEW

**Comment by filipw** [comment]
thanks a lot! Can you update MsBuild version in `build.cmd` to 15.0? 
Also, let's set the language version to `latest` rather than pinning a specific one.

**Review by filipw — CHANGES_REQUESTED** [review]
`build.cmd` needs an update otherwise it won't build on the CI server

**Comment by chergey** [comment]
updated

**Comment by chergey** [comment]
Is there anything else left ?

**Review by filipw — APPROVED** [review]

**Comment by filipw** [comment]
thanks!

**Pull request merged**
