### PR TITLE
(Fix #891) Add an error message if unable to load a module.

### LINKED ISSUE #891: Passing an unknown module fails silently
image

### PR DESCRIPTION
**Pull request by mattico**
```
> scriptcs.exe -m "foo,bar,baz"
ERROR: Unable to load module: foo
ERROR: Unable to load module: bar
ERROR: Unable to load module: baz
scriptcs (ctrl-c to exit or :help for help)

> > ^C
```

Should there be tests for this kind of thing?

### CODE REVIEW

**Comment by glennblock** [comment]
@mattico sorry for the long delay. This seems like a reasonable fix to me. Can you add a unit test?

**Comment by glennblock** [comment]
@mattico I am going to go ahead and add a unit test. Thanks!

**Comment by mattico** [comment]
@glennblock Oh sorry, forgot about this. Feel free. 👍

**Comment by glennblock** [comment]
I am having some issues getting this to work consistently. I am going to hold off for now.

**Pull request closed without merging**
