### PR TITLE
implemented CommandLine.UnexpectedOption

### LINKED ISSUE #869: Default to REPL when other options are passed
For a bare command with no options, i.e. `scriptcs`, the presence of a script name determines whether to enter the REPL (with the `-repl` option forcing exit to REPL even when there *is* a script name).

However, as soon as any other option is provided, e.g. `-modules "mono"` or `-debug`, the `-repl` option *must* be provided otherwise invalid usage is assumed and the usage is shown in the console. IMO this is nasty UX. It bites me *every single time* I try to run the REPL with the mono engine :tired_face:.

### LINKED ISSUE #895: Process does not error when an unexpected CLI arg is passed
image

Regression introduced in https://github.com/scriptcs/scriptcs/pull/890

### PR DESCRIPTION
**Pull request by adamralph**
fixes #869 

needs to be merged before we can release 0.13 - see https://github.com/scriptcs/scriptcs/issues/869#issuecomment-69059235

### CODE REVIEW

**Comment by adamralph** [comment]
There are plenty more opportunities to refactor and simplify the arguments implementation but I decide to draw a line under what I've done so far and send this PR, since we need to close #869 before the 0.13 release, and I need to get back onto #865 which also needs to be fixed for 0.13 to go live.

**Comment by adamralph** [comment]
I did a test rebase of my work on closing #626 onto this branch and there were some tricky conflicts so I decide to resolve them and leave my work for #626 based on this branch.

This means the sooner we can get this PR merged the better, since it's now the blocker for all work required to push out 0.13.

**Comment by adamralph** [comment]
BTW, the easiest way to review this PR may be one commit at a time, since each is well isolated with a specific purpose.

**Comment by khellang** [comment]
Removing nesting doesn't diff very well in general :wink:

**Comment by adamralph** [comment]
Some local diff apps do it quite well if you toggle off 'compare whitespace'. I sent a feature request to GitHub for that a while back but they've not responded so far.

**Comment by khellang** [comment]
That's actually very true! Tried https://github.com/scriptcs/scriptcs/pull/896/files?w=1, works like a charm. You knew about `?w=1`, right?

**Comment by adamralph** [comment]
I'd forgotten about it, but thanks for reminding me :wink:. I guess it would ultra trivial to add a UI control for it then...

**Comment by khellang** [comment]
LOL. Yeah, it's _really_ weird that it they haven't added it yet. The query param has been there for years.

**Comment by adamralph** [comment]
@scriptcs/core I decided to remove the arguments/config file refactoring commits from this PR because they were bloating it and I think that whole space actually needs a re-write instead (see #897).

This PR is much simpler now and only contains one refactoring commit for the acceptance tests. Would anyone have time to look at it over the weekend?

**Comment by adamralph** [comment]
Can anyone look at this? We need to move forward with the nightly because the situation with the folder migration is already starting to confuse people, e.g. https://github.com/scriptcs/scriptcs-samples/issues/20.

**Comment by adamralph** [comment]
Awesomeness dude. PR for #626 coming soon...

**Pull request merged**
