### PR TITLE
restore deprecated Common.Logging overloads #847

### LINKED ISSUE #847: Deprecate Common.Logging usage in favour of our own logging API
Let's drop Common.Logging which is an extra dependency that has already caused a number of issues in terms of assembly versioning, binding redirects and what not.

I propose we just use LibLog (https://github.com/damianh/LibLog) which is a single class file that you just copy paste.

### PR DESCRIPTION
**Pull request by adamralph**
Fixes #847

This restores all the Common.Logging members as per version 0.14.1.

### CODE REVIEW

**Comment by adamralph** [comment]
Comparing the branch to 0.14.1 is a little challenging since there have been so many other changes since, but it the diff can be seen at https://github.com/scriptcs/scriptcs/compare/v0.14.1...adamralph:847

**Comment by adamralph** [comment]
Incidentally, we may be able to use the ParticularLabs APIComparer to perform a static analysis of breaking changes between 0.14.1 and the 847 branch. See https://github.com/ParticularLabs/APIComparer/blob/b207b536d6898980192f695def2b503adcbf9127/APIComparer/Program.cs#L18

**Comment by adamralph** [comment]
Travis is broken because of NuGet.Core renaming shenanigans. That should be fixed by https://github.com/scriptcs/scriptcs/pull/1069, which can go in before this PR.

**Comment by adamralph** [comment]
This should be good to go now.

**Comment by filipw** [comment]
ok great job, but i have trouble comprehending how does Autofac chooses the constructor now?

**Comment by adamralph** [comment]
Dunno, it just works :stuck_out_tongue_closed_eyes: 

But actually, we don't do magic scanning and injection, right? We explicitly register types in `RuntimeServices` and wotnot? (I'm easily lost in this part of the codebase.)

**Comment by khellang** [comment]
Since we don't register a `Common.Logging.ILog`, but a [`ILogProvider`](https://github.com/scriptcs/scriptcs/blob/dev/src/ScriptCs.Hosting/RuntimeServices.cs#L58), Autofac can only satisfy one ctor :smile:

**Comment by filipw** [comment]
ah!

**Comment by filipw** [comment]
LGTM

**Comment by adamralph** [comment]
woot! thanks @filipw

**Pull request merged**
